name: Reusable Worflow

on:
  workflow_call:
  
jobs:
  run2-job1:
    runs-on : ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -name: Write something to log
      run: | 
        echo: "I am reusable workflow Two"
      
